name: activerecord
version: 0.0.4
author: Axel Christ <adracus@gmail.com>
description: An Active Record implementation for the Dart language
homepage: https://github.com/Adracus/ActiveRecord
dependencies:
  postgresql: ">=0.2.13 <0.3.0"
dev_dependencies:
  unittest: any
  args: any
