name: activerecord
version: 2.0.0
author: Axel Christ <adracus@gmail.com>
description: An Active Record implementation for the Dart language
homepage: https://github.com/Adracus/ActiveRecord
dependencies:
  logging: ">=0.9.1+1 <0.10.0"
  json_object: ">=1.0.18+2 <2.0.0"
dev_dependencies:
  unittest: any
  args: any
  postgres_adapter: ">=0.0.1 <=0.1.0"